import {
  Category,
  Location,
  Product,
  Supplier,
  User,
  Sale,
  Purchase,
  InventoryMovement,
  CashRegister,
  CashMovement,
  CostHistory,
  StockAlert,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    nombre: 'Carlos',
    apellido: 'Mendoza',
    correo: 'admin@ferroget.com',
    rol: 'ADMINISTRADOR',
    estado: 'ACTIVO',
    fecha_creacion: '2026-01-15T08:00:00Z',
  },
  {
    id: 2,
    nombre: 'Elena',
    apellido: 'Rivas',
    correo: 'vendedor@ferroget.com',
    rol: 'VENDEDOR',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-01T08:30:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 1, nombre: 'Herramientas eléctricas', descripcion: 'Maquinaria y herramientas motrices eléctricas y a batería', estado: 'ACTIVO' },
  { id: 2, nombre: 'Herramientas manuales', descripcion: 'Herramientas de mano mecánicas de taller y obra', estado: 'ACTIVO' },
  { id: 3, nombre: 'Materiales de construcción', descripcion: 'Cemento, áridos, adhesivos y aditivos', estado: 'ACTIVO' },
  { id: 4, nombre: 'Ferretería general', descripcion: 'Tornillería, clavos, bisagras y cerrajería', estado: 'ACTIVO' },
  { id: 5, nombre: 'Electricidad', descripcion: 'Cables, tomacorrientes, interruptores e iluminación', estado: 'ACTIVO' },
  { id: 6, nombre: 'Plomería', descripcion: 'Tuberías PVC, llaves de paso, pegamentos y accesorios', estado: 'ACTIVO' },
];

export const INITIAL_LOCATIONS: Location[] = [
  { id: 1, nombre: 'Zona Frontal - Herramientas', descripcion: 'Exhibidores principales de herramientas', pasillo: 'Pasillo 1', estante: 'Estante A' },
  { id: 2, nombre: 'Zona Frontal - Cerrajería', descripcion: 'Pared de herramientas manuales', pasillo: 'Pasillo 1', estante: 'Estante B' },
  { id: 3, nombre: 'Zona Media - Eléctricos', descripcion: 'Estantería metálica de electricidad', pasillo: 'Pasillo 2', estante: 'Estante A' },
  { id: 4, nombre: 'Zona Media - Fijaciones', descripcion: 'Gavetas clasificadas de tornillería', pasillo: 'Pasillo 2', estante: 'Estante B' },
  { id: 5, nombre: 'Zona Trasera - Plomería', descripcion: 'Racks de tubos y conexiones PVC', pasillo: 'Pasillo 3', estante: 'Estante A' },
  { id: 6, nombre: 'Almacén de Carga', descripcion: 'Área de sacos de cemento y materiales pesados', pasillo: 'Patio Posterior', estante: 'Zona Cemento' },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 1,
    razon_social: 'Distribuidora Industrial Ferretera S.A.',
    identificacion: '1792345678001',
    telefono: '+593 2 290 4500',
    correo: 'ventas@ferreteraindustrial.com',
    direccion: 'Av. Las Palmeras 405 y Galápagos',
    estado: 'ACTIVO',
  },
  {
    id: 2,
    razon_social: 'Cementos & Materiales del Norte Cía. Ltda.',
    identificacion: '1798765432001',
    telefono: '+593 2 250 1200',
    correo: 'pedidos@cementosdelnorte.com',
    direccion: 'Parque Industrial Norte, Lote 12',
    estado: 'ACTIVO',
  },
  {
    id: 3,
    razon_social: 'ElectroCables del Pacífico S.A.',
    identificacion: '0991234567001',
    telefono: '+593 4 233 8900',
    correo: 'contacto@electrocablespacifico.com',
    direccion: 'Vía Daule Km 8.5',
    estado: 'ACTIVO',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    codigo: 'HER-E001',
    nombre: 'Taladro Percutor 750W 1/2"',
    descripcion: 'Velocidad variable reversible con mandril de 1/2 pulgada y maletín de transporte.',
    categoria_id: 1,
    ubicacion_id: 1,
    precio_compra: 42.50,
    precio_venta: 68.00,
    stock_actual: 8,
    stock_minimo: 4,
    unidad_medida: 'UNIDAD',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-10T09:00:00Z',
  },
  {
    id: 2,
    codigo: 'HER-M002',
    nombre: 'Martillo de Uña 16 oz Cabo Fibra',
    descripcion: 'Cabeza de acero forjado templado con mango ergonómico antideslizante.',
    categoria_id: 2,
    ubicacion_id: 2,
    precio_compra: 5.20,
    precio_venta: 9.50,
    stock_actual: 15,
    stock_minimo: 6,
    unidad_medida: 'UNIDAD',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-10T09:15:00Z',
  },
  {
    id: 3,
    codigo: 'HER-M003',
    nombre: 'Juego Destornilladores 6 Piezas',
    descripcion: 'Puntas imantadas planas y Phillips aisladas en cromo vanadio.',
    categoria_id: 2,
    ubicacion_id: 2,
    precio_compra: 7.80,
    precio_venta: 13.90,
    stock_actual: 12,
    stock_minimo: 5,
    unidad_medida: 'JUEGO',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-10T09:30:00Z',
  },
  {
    id: 4,
    codigo: 'HER-M004',
    nombre: 'Alicate Universal 8" Aislado 1000V',
    descripcion: 'Acero de alto carbono con filo templado por inducción para cables duros.',
    categoria_id: 2,
    ubicacion_id: 2,
    precio_compra: 6.50,
    precio_venta: 11.50,
    stock_actual: 3, // Stock Bajo (<= 5)
    stock_minimo: 5,
    unidad_medida: 'UNIDAD',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-10T09:40:00Z',
  },
  {
    id: 5,
    codigo: 'HER-M005',
    nombre: 'Llave Inglesa Ajustable 10"',
    descripcion: 'Apertura de quijada de hasta 32mm graduada en milímetros.',
    categoria_id: 2,
    ubicacion_id: 2,
    precio_compra: 8.90,
    precio_venta: 15.00,
    stock_actual: 7,
    stock_minimo: 4,
    unidad_medida: 'UNIDAD',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-10T10:00:00Z',
  },
  {
    id: 6,
    codigo: 'MAT-C006',
    nombre: 'Cemento Portland Especial 50kg',
    descripcion: 'Cemento para estructuras de alta resistencia y fraguado uniforme.',
    categoria_id: 3,
    ubicacion_id: 6,
    precio_compra: 6.80,
    precio_venta: 8.50,
    stock_actual: 45,
    stock_minimo: 20,
    unidad_medida: 'SACO',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-11T08:00:00Z',
  },
  {
    id: 7,
    codigo: 'PLO-T007',
    nombre: 'Tubo PVC Sanitario 1/2" x 3m',
    descripcion: 'Tubo de presión para conducción de agua potable norma técnica.',
    categoria_id: 6,
    ubicacion_id: 5,
    precio_compra: 2.10,
    precio_venta: 3.80,
    stock_actual: 2, // Stock Crítico / Bajo
    stock_minimo: 10,
    unidad_medida: 'TUBO',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-11T09:00:00Z',
  },
  {
    id: 8,
    codigo: 'ELE-C008',
    nombre: 'Cable Eléctrico #12 AWG THHN 100m',
    descripcion: 'Conductor de cobre electrolítico de 99.9% pureza recubierto de PVC antillama.',
    categoria_id: 5,
    ubicacion_id: 3,
    precio_compra: 38.00,
    precio_venta: 54.00,
    stock_actual: 6,
    stock_minimo: 4,
    unidad_medida: 'ROLLO',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-11T10:00:00Z',
  },
  {
    id: 9,
    codigo: 'FER-T009',
    nombre: 'Tornillos para Madera 1 1/2" (Caja 100u)',
    descripcion: 'Tornillo autorroscante cabeza plana avellanada zincado brillante.',
    categoria_id: 4,
    ubicacion_id: 4,
    precio_compra: 2.30,
    precio_venta: 4.50,
    stock_actual: 25,
    stock_minimo: 10,
    unidad_medida: 'CAJA',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-12T08:30:00Z',
  },
  {
    id: 10,
    codigo: 'HER-B010',
    nombre: 'Juego Brocas Concreto 3/8" a 1/2" (5u)',
    descripcion: 'Brocas con punta de carburo de tungsteno para taladros percutores.',
    categoria_id: 1,
    ubicacion_id: 1,
    precio_compra: 4.50,
    precio_venta: 8.20,
    stock_actual: 1, // Stock Crítico
    stock_minimo: 5,
    unidad_medida: 'JUEGO',
    estado: 'ACTIVO',
    fecha_creacion: '2026-02-12T09:00:00Z',
  },
];
